services:
  golang:
    container_name: go_app
    build:
      context: .
      dockerfile: .docker/golang/Dockerfile.dev
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"]
